import * as THREE from 'three';

/**
 * Export a Three.js BufferGeometry to STL format (binary)
 * Binary STL is more compact than ASCII
 */
export function exportToSTL(geometry: THREE.BufferGeometry, filename: string = 'cookie-cutter.stl'): void {
  const stlData = geometryToSTL(geometry);
  downloadBlob(stlData, filename, 'application/octet-stream');
}

/**
 * Convert Three.js BufferGeometry to binary STL ArrayBuffer
 */
export function geometryToSTL(geometry: THREE.BufferGeometry): ArrayBuffer {
  // Ensure we have the index
  const nonIndexedGeometry = geometry.index ? geometry.toNonIndexed() : geometry;

  const positions = nonIndexedGeometry.attributes.position.array;
  const numTriangles = positions.length / 9;

  // Binary STL format:
  // - 80 bytes header
  // - 4 bytes number of triangles (uint32)
  // - For each triangle:
  //   - 12 bytes normal (3 x float32)
  //   - 36 bytes vertices (3 vertices x 3 coords x float32)
  //   - 2 bytes attribute byte count (uint16, usually 0)
  const bufferSize = 80 + 4 + numTriangles * 50;
  const buffer = new ArrayBuffer(bufferSize);
  const dataView = new DataView(buffer);

  // Write header (80 bytes)
  const header = 'Cookie Cutter STL - Generated by Cookie Cutter Generator';
  for (let i = 0; i < 80; i++) {
    dataView.setUint8(i, i < header.length ? header.charCodeAt(i) : 0);
  }

  // Write number of triangles
  dataView.setUint32(80, numTriangles, true);

  let offset = 84;

  for (let i = 0; i < numTriangles; i++) {
    const baseIdx = i * 9;

    // Get vertices
    const v1 = new THREE.Vector3(positions[baseIdx], positions[baseIdx + 1], positions[baseIdx + 2]);
    const v2 = new THREE.Vector3(positions[baseIdx + 3], positions[baseIdx + 4], positions[baseIdx + 5]);
    const v3 = new THREE.Vector3(positions[baseIdx + 6], positions[baseIdx + 7], positions[baseIdx + 8]);

    // Calculate normal
    const edge1 = new THREE.Vector3().subVectors(v2, v1);
    const edge2 = new THREE.Vector3().subVectors(v3, v1);
    const normal = new THREE.Vector3().crossVectors(edge1, edge2).normalize();

    // Write normal
    dataView.setFloat32(offset, normal.x, true);
    dataView.setFloat32(offset + 4, normal.y, true);
    dataView.setFloat32(offset + 8, normal.z, true);
    offset += 12;

    // Write vertices
    dataView.setFloat32(offset, v1.x, true);
    dataView.setFloat32(offset + 4, v1.y, true);
    dataView.setFloat32(offset + 8, v1.z, true);
    offset += 12;

    dataView.setFloat32(offset, v2.x, true);
    dataView.setFloat32(offset + 4, v2.y, true);
    dataView.setFloat32(offset + 8, v2.z, true);
    offset += 12;

    dataView.setFloat32(offset, v3.x, true);
    dataView.setFloat32(offset + 4, v3.y, true);
    dataView.setFloat32(offset + 8, v3.z, true);
    offset += 12;

    // Write attribute byte count (0)
    dataView.setUint16(offset, 0, true);
    offset += 2;
  }

  return buffer;
}

/**
 * Export to ASCII STL format (larger but human-readable)
 */
export function geometryToSTLAscii(geometry: THREE.BufferGeometry): string {
  const nonIndexedGeometry = geometry.index ? geometry.toNonIndexed() : geometry;
  const positions = nonIndexedGeometry.attributes.position.array;
  const numTriangles = positions.length / 9;

  let stl = 'solid cookie-cutter\n';

  for (let i = 0; i < numTriangles; i++) {
    const baseIdx = i * 9;

    const v1 = new THREE.Vector3(positions[baseIdx], positions[baseIdx + 1], positions[baseIdx + 2]);
    const v2 = new THREE.Vector3(positions[baseIdx + 3], positions[baseIdx + 4], positions[baseIdx + 5]);
    const v3 = new THREE.Vector3(positions[baseIdx + 6], positions[baseIdx + 7], positions[baseIdx + 8]);

    const edge1 = new THREE.Vector3().subVectors(v2, v1);
    const edge2 = new THREE.Vector3().subVectors(v3, v1);
    const normal = new THREE.Vector3().crossVectors(edge1, edge2).normalize();

    stl += `  facet normal ${normal.x} ${normal.y} ${normal.z}\n`;
    stl += `    outer loop\n`;
    stl += `      vertex ${v1.x} ${v1.y} ${v1.z}\n`;
    stl += `      vertex ${v2.x} ${v2.y} ${v2.z}\n`;
    stl += `      vertex ${v3.x} ${v3.y} ${v3.z}\n`;
    stl += `    endloop\n`;
    stl += `  endfacet\n`;
  }

  stl += 'endsolid cookie-cutter\n';

  return stl;
}

function downloadBlob(data: ArrayBuffer | string, filename: string, mimeType: string): void {
  const blob = new Blob([data], { type: mimeType });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}
